### ISSUE TITLE
Q2

### ISSUE THREAD

**Issue by lgtian** [richardissuperman/WHUT_CS_CLASS_09#17]
谢谢仔仔的分享:kissing_heart: :kissing_heart:，新美大叼叼哒~~。门外汉请教两个问题：
 > -  文档提到了挺多抽象的概念，云主机就是其中之一，感觉创建云主机是一个挺重的任务，不知这个任务的成本有多少（当然不同需求的成本是不一样的，最小是多少呢？）
> - 另外，想了解一下云主机创建的方式和时机有哪些？文中提到“外界API请求Region创建云主机”，这表示美团云给外部提供了创建云主机的服务对吧，那暴露给外部的配置参数有哪些呢？个人感觉创建云主机对用户透明比较好，只暴露给他们服务，云架构根据服务所需自主创建云主机。

**Comment by HusterWan** [comment]
田哥不好意思，才看到你提的问题，不过田哥提的问题都非常好。
第一个问题，田哥是要问云主机创建时间吧？这个指标对云计算厂商来说是一项非常重要的SLA，我们每天会统计美团各个云平台创建云主机时间（top99，top90，top50）。确实，因为云主机有不同类型，所以创建时间肯定有很大差异，现在云平台主要有三种类型的云主机，baremetal，vm和docker。这三类云主机的创建时间差异还是比较大的：
baremetal：就是我们平常说的服务器，创建baremetal的过程就是服务器一个自动化装机的过程，创建baremetal经过好几次的优化，现在时间大约在600～700s左右。
vm：就是我们说的kvm 虚拟机，这个时间现在大约在80s左右
docker：大家称的轻量型vm，因为docker的容器是和宿主机共有内核，所以启动速度非常快，一个docker的容器启动时间在1s左右，所以创建docker 容器的时间也非常短，现在平均在20s左右能完成整个过程，如果排除调度时间，一个docker容器创建时间能在6s内就完成。

第二个问题，是关于云平台给外界提供服务接口的问题，一般的用户直接在web页面可视化操作就是OK的，因为量小的用户，直接在web页面管理自己的云主机资源就OK。但是像拥有云主机数量比较庞大，或者懂技术的用户，希望通过API接口来管理和运维自己的云主机，所以云平台还需要提供API接口调用方式——ec2接口，田哥如果有兴趣，可以去美团云官网查看相关ec2的文档：https://mos.meituan.com/doc/api/common/common/index

**Comment by lgtian** [comment]
仔仔犀利:thumbsup::thumbsup:，解答非常详细。
