### ISSUE TITLE
视频水印的问题

### ISSUE THREAD

**Issue by richardissuperman** [richardissuperman/WHUT_CS_CLASS_09#18]
感谢春哥的分享！最近也是在做安卓平台发播放器相关的工作，打算把FFMPEG直接移植到安卓平台上(之前一直使用安卓原生的Media API，有很多兼容问题)
回到正题，关于解复用和解码部分，
>解复用将容器中的视频压缩数据按照格式规定提取出来，在FFmpeg的实现方法非常简单，里面的packet就是每一帧图像的压缩数据。

我想问一下，每一帧的图像数据是根据什么来获得的呢？
我知道比如像mp4格式的容器，一般会有一个索引表，对应每一个时间段内的sample数据，但是具体到每一帧的话，应该怎么获取呢？而且你的code里面貌似也没有对应的参数。
不知道春哥可不可以从原理和代码的角度来讲解一下
谢啦！！！

**Comment by richardissuperman** [comment]
@barry963

**Comment by barry963** [comment]
庆哥问的很专业，首先我的code里面没有参数是因为FFmpeg按照解码顺序一帧一帧的返回数据，水印流程需要逐帧检测。其次如果具体到某一帧可以直接遍历直到那一帧，如果需要具体某一个播放帧的话这里就涉及到一个问题，对于有些codec来说，解码顺序不等于播放顺序，所以遍历的时候需要利用AVpacket里面的pts（播放时间戳），文档在[这里](https://ffmpeg.org/doxygen/3.2/structAVPacket.html#a73bde0a37f3b1efc839f11295bfbf42a)，遍历之前先计算出播放帧对应的时戳然后遍历每一帧直到获取，具体代码如下

```C
//假设目标帧为target
int target = input_target_frame;
//计算目标帧的时戳，frame_rate就是帧速率，比如23帧/s
double time_stamp = target/frame_rate;
//遍历
while(av_read_frame(pFormatCtx, &packet))
{
  //这里比较每次的packet里面的时戳
  if (IsTargetFrame(packet->pts, time_stamp))
  {
     //操作
     break;
  }
}
```

如果具体到某一个解码帧的话就很简单了，直接用个计数器就行。

内部的原理我没有研究过源代码，能想到的直接方法正如你说的那样，比如mp4，里面有个stsc，stco/co64等等几个box描述了chunk（若干个sample为一个chunk）的索引，解复用的时候先解析索引，然后从第一个chunk的第一个sample开始，按照标准里面规定的每个帧开头和结束的字符，一帧一帧的解析。

希望以上能回答你的问题 :smile:  @richardissuperman

**Comment by lgtian** [comment]
感谢春哥的分享，目前为止在工作中还没有接触过水印相关的内容，毕竟是在国外啊:thumbsup::thumbsup:。

春哥所在组做视频水印的目的主要是版权保护对吧，文中也提到主要的实现方式是在视频图像中加入额外数据（比如供应商的ID，设备的mac地址）。

加进去只是第一步，要做真伪鉴别必须再把加入的数据提取出来对吧，我想问的是应该如何规避他人提取水印数据的能力？如果水印数据被他人提取出来，是不是就可以伪造水印了？

**Comment by richardissuperman** [comment]
soga,所以说每一帧还是有对应的时间戳是么？那这个时间戳的信息是存在容器的atom header里面还是在帧的数据里面啊？
最后一个问题就是，某些codec的解码顺序不同与播放顺序，那么播放的时候是不是就是按照上述的时间戳来维护顺序的？可否也粗略的讲解一下codec对视频和音频文件做解码的时候如何进行sync呢，还有通常情况下视频音频出现不同步的原因。。。。。(问题好多哈哈)
@barry963

**Comment by barry963** [comment]
问得好，哈哈，我们这边是有一个鉴别真伪的探测器，用来提取水印，规避盗版的方法有两个方面，
第一个是水印自身的反盗版能力。水印是一种对称加密，用数学操作把数据加入图片当中，如果盗版商不知道这个数学过程就很难反向提取出内部的水印，同样，也很难伪造水印，
第二个是水印帧的位置，文章里面提到了过滤这个步骤，不同的配置会让水印帧分布在不同的位置，即使盗版商能够找到一些水印帧并把它们去掉，剩下的水印帧也能检测出加入的数据。

不知道我说清楚了没有 :smile: @lgtian

**Comment by lgtian** [comment]
@barry963 解答的非常清楚 :grinning::grinning:

**Comment by barry963** [comment]
庆哥对这个这么有兴趣 :smile: 
> 那这个时间戳的信息是存在容器的atom header里面还是在帧的数据里面啊？

跟具体codec格式有关，我了解的AVC/H.264的帧数据大部分都没有pts，少部分情况下由SEI这个atom提供，所以大部分情况在容器里面atom里面（不是header，header描述大小和种类

> 某些codec的解码顺序不同与播放顺序，那么播放的时候是不是就是按照上述的时间戳来维护顺序的？可否也粗略的讲解一下codec对视频和音频文件做解码的时候如何进行sync呢

同步问题我没搞过 :sob: ，刚才谷歌了才知道，[这里](http://dranger.com/ffmpeg/tutorial05.html)看到，里面都是用pts来维护的，一般三种同步方式，
- video sync audio
- audio sync video
- video 和 audio 同步电脑时钟

> 还有通常情况下视频音频出现不同步的原因

这个我也不清楚 :sob: 刚才在[这里](https://www.quora.com/What-are-the-most-common-reasons-why-audio-and-video-are-out-of-sync-when-you-watch-Internet-streamed-videos)看到解答讲网络视频的非同步问题，很有道理，因为不少网络视频是动态帧速率，如果原始视频的codec有问题，上传之后由网站再编码会损坏甚至丢失pts。

我水平有限，有问题再一起讨论 :smile_cat:  @richardissuperman

**Comment by HusterWan** [comment]
@barry963 
哈哈，春哥，赞美之词不多说啦，门外汉提三个小问题：

> /定义容器格式context
AVFormatContext *pformatCtx;
//打开容器，获取容器context信息
avformat_open_input(&pformatCtx, inputFile, NULL, NULL);
//定义解复用之后的帧压缩数据
AVPacket packet;
//解复用
av_read_frame(pFormatCtx, &packet);

1、看你贴出来的代码，视频文件解压缩是否直接将文件全部读到内存中？按照你文中开头介绍的，一个视频文件解码出来的数据应该是很庞大的吧？那按照：解码＝>过滤＝>水印＝>编码，这样一个完整流程，处理一部2个多小时的美国大片大约是多长时间？

2、还有就是做为门外汉，我比较感兴趣的一个问题是：一个视频文件盗版检测的大体过程？依我的了解，视频文件盗版检测好像是一个非常快的过程，举个个人实例：前段时间国内当时特别火的一部电视剧《人民的名义》的送审样片被别人恶意流传到网上，我当时也正在追这个剧，突然知道百度云盘上正在流传这个样片，当时想下载下来，结果为时已晚，下载文件时，我傻逼的试过该文件名和文件后缀，结果发现百度云盘很快就识别出视频文件内含有敏感内容，禁止下载。所以，我猜测百度云这种盗版检测是不是就是对视频文件中某部分md5值的对比？个人觉得这种方式会很快，如果按照检查水印的方式的话，可能会比较耗时吧？

3、最后问一个邪恶的问题，春哥公司有没有做视频鉴黄检测方面的研究？

**Comment by richardissuperman** [comment]
感谢春哥！我懂啦!

@barry963

**Comment by barry963** [comment]
@HusterWan 仔仔不要谦虚
先来回答第三个问题，
没有，哈哈，不过可以有，之前见过其他组做logo检测的研究，应该可以迁移到鉴黄上面来，到时候聘请仔仔当principal detection scientist :smiley_cat: 

第一个问题，不会直接读取到内存中，代码是一个示意程序，实际中会有个循环，每次操作一个帧就不大了。两个小时的电影处理时间跟
- codec 格式
- 像素
- 比特数

都有关系，如果是一个普通1020p,8-bit的mpeg-2电影，基本可以达到2小时，也就是实时水印，如果是一个3840p (4k), 10-bit 的jpeg2000外加HDR支持，就需要很久了，大概七八个小时，虽然有很多速度优化的办法，但是要实时很难。

第二个问题，我们这边的检测流程就是首先有一个巨大的爬虫程序，搜遍网上所有我们可能加过水印的电影，然后再进行水印检测。你说的应该就是相当于在爬虫阶段就被检测出来直接屏蔽了，百度的方法我也不太清楚，它应该就像你说的用个md5什么的检测，或者直接找到源头然后根据分享记录封杀所有的拷贝。我们公司的情况跟百度不太一样，后者属于平台提供商，有权利封锁任何可疑的盗版，宁可错杀三千不可放过一个，它只要判断这是一个本应该由官方发布的视频就够了，比如核实一个用户举报。而我们是技术提供商，提供从加水印到检测技术，把最终的盗版检测结果交给买我们技术的电影厂，至于他们怎么办，报警还是炸掉盗版网站我们就不管了 :smile: 另外，检测速度听说还可以，多加几个服务器就行哈哈哈

**Comment by richardissuperman** [comment]
春哥下次再轮到你分享的时候不知道可不可以说一下关于硬件解码和软件解码的知识 😸  

@barry963

**Comment by barry963** [comment]
@richardissuperman 小伙子求知欲很强啊。这个问题我知道一点，之前搞过硬件解码的东西，但是不知道从何讲起，能不能给点方向。以下我先试着说一点：

总体来说这两种解码，软件就是用通用计算机架构比如X86走通用流程（比如取指令，解指令，计算，存取），硬件就是用FPGA甚至是制作专用芯片（ASIC）根据解码算法直接实现。软件的好处就是通用性强，同样的架构哪里都能跑，修改容易，开发速度快，成本低，坏处就是速度慢，功耗高受制于指令流程。硬件好处就是速度快，功耗低，但是修改难，开发度速慢，成本很高。FPGA好一点，它属于硬件编程，有软件的所有优点，但是开发速度相对于软件还是慢一些，介于软件和纯硬件之间。

**Comment by richardissuperman** [comment]
@barry963 
哈哈因为虽然我们做视频播放，但是做应用的很多时候接触不到底层，我又很感兴趣，最近有个proposal去把项目里面使用的安卓原生的MediaCodec(安卓的api应该是用硬件解码，所以我们的应用有很多兼容问题，比如华为的某些机子莫名的黑屏。。)替换成FFMPEG。所以对这方面想多了解一下。

我就想大概了解一下，针对硬件的编程，有没有例子，比如你的GPU事Nividia的，那么是不是在编程的时候要使用Nividia自己提供的一些library来编程才能使用GPU来帮助计算。因为应用层很多东西都封装好了，比如安卓自己有硬件加速帮助渲染UI，但是在java的应用层就是一个api的事情，深入到底层，C的代码是怎么调用GPU的我想了解一下。

最后如果能稍微介绍一下FFMPEG这个library的结构的话最好啦！

问题有点多春哥。。。。见谅 😈

**Comment by barry963** [comment]
@richardissuperman 
才想起来需要回答这个问题 :cry:

关于庆哥提到的GPU硬件编程的问题，我的理解是，这些其实是软件编程，因为硬件编程需要直接操作硬件，比如单片机编程，需要用到中断向量，输入端口等等，而Nividia的GPU操作已经有封装好的API可以调用了，用户可以直接平行化数据操作，相当于在硬件和用户之间加了一层。当然，正如你所说，需要Nivdia提供的library。具体实现方式就跟WINDOWS或者linux下面如何管理硬件有关了，GPU在计算机里面都注册有自己的操作地址，通过driver对外提供接口。调用的时候，通过函数名经过一层层封装到对应的library再到一直到寄存器级别然后完成操作。

关于ffmpeg的结构介绍，推荐这位大神的[博客](http://blog.csdn.net/leixiaohua1020/article/details/15811977)，非常实用。

不知道有没有回答清楚。

**Comment by richardissuperman** [comment]
感谢春哥！！我接下来打算把我们安卓端的api更换成ffmpeg的，到时候有问题再问你！么么哒

@barry963
